// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRWijsmT7f6t2JcmJBe6dakDMquD1NTw',
    appId: '1:315995254709:web:530b30e40016ddbdbfb3fc',
    messagingSenderId: '315995254709',
    projectId: 'fypuserapp',
    authDomain: 'fypuserapp.firebaseapp.com',
    storageBucket: 'fypuserapp.appspot.com',
    measurementId: 'G-9TCM18K1ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtF05pubnAmLGJqGOe8RUHcGzu2r09uuA',
    appId: '1:315995254709:android:f1e9aa5882e69f3dbfb3fc',
    messagingSenderId: '315995254709',
    projectId: 'fypuserapp',
    storageBucket: 'fypuserapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFeBjM_QyIDb3Kh-ngvpQduASB4el5Do',
    appId: '1:315995254709:ios:a77233356afd2d1cbfb3fc',
    messagingSenderId: '315995254709',
    projectId: 'fypuserapp',
    storageBucket: 'fypuserapp.appspot.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFeBjM_QyIDb3Kh-ngvpQduASB4el5Do',
    appId: '1:315995254709:ios:a77233356afd2d1cbfb3fc',
    messagingSenderId: '315995254709',
    projectId: 'fypuserapp',
    storageBucket: 'fypuserapp.appspot.com',
    iosBundleId: 'com.example.userApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZRWijsmT7f6t2JcmJBe6dakDMquD1NTw',
    appId: '1:315995254709:web:77a4cc545a640e72bfb3fc',
    messagingSenderId: '315995254709',
    projectId: 'fypuserapp',
    authDomain: 'fypuserapp.firebaseapp.com',
    storageBucket: 'fypuserapp.appspot.com',
    measurementId: 'G-3VS9GS619H',
  );
}
